apiVersion: v1
kind: Service
metadata:
  name: backend-local
  namespace: monitoring
  labels:
    app: backend-local
spec:
  type: ExternalName
  externalName: 192.168.7.237   # <-- your Windows host IP
  ports:
    - port: 5000
      targetPort: 5000
      name: http
