apiVersion: v1
kind: Service
metadata:
  name: backend-local
  namespace: monitoring
  labels:
    app: backend-local
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 5000
      targetPort: 5000
      name: http
