apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-local-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-local
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
