apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend          # 👈 REQUIRED for ServiceMonitor
spec:
  selector:
    app: backend
  ports:
    - name: http          # 👈 IMPORTANT (port name)
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
